######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 27 09:01:15 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
