######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 27 09:18:46 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += number.cpp
