######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 27 08:50:13 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quitButton.cpp
