######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 26 18:05:07 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
