######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 27 08:56:09 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += account.cpp
