######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 28 09:17:02 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += coordinate_label.h
SOURCES += coordinate_label.cpp main.cpp
